---
title: "Wokrout3-sharene-siddiqui"
author: "Sharene Siddiqui"
date: "4/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

```{r}
# 1.1) Private Checker Functions

# check if prob is valid. Valid prob must be between 0 and 1 
check_prob <- function(p){
  if ((p < 0) | (p > 1)){
    stop("p must be a number between 0 and 1")
  }
  else{
    return (TRUE)
  }
}

#Check if valid value for number of trials. Valid number is a non-negative integer
check_trials <- function(n){
  if (n %% 1 != 0){
    stop("n must be an integer")
  } 
  if (n < 0){
    stop("n must be a non-negative value")
  }
  else{
    return(TRUE)
  }
}

 
#Check if valid value for number of successes. Valid number is between 0 and number of trials.
check_success <- function(n, k){
  check_trials(n)
  if (any (k > n)){
    stop("success cannot be greater than trials")
  }
  else if (any(k < 0) | !is.numeric(k)){
    stop("invalid success value")
  }
  else{
    return(TRUE)
  }
}

```

```{r}
# 1.2) Private Auxiliary Functions

#mean of binomial distribution
aux_mean <- function(n, p){
  mean <- n*p
  return(mean)
}

#variance of binomial distrubtion
aux_variance <- function(n, p){
  var <- n*p*(1-p)
  return(var)
}

#mode of binomial distribution
aux_mode <- function(n, p){
  mode <- as.integer(n*p + p)
  return(mode)
}

#skewness of binomial distribution
aux_skewness <- function(n, p){
  skew <- (1-2*p)/(sqrt(n*p*(1-p)))
  return(skew)
}

#kurtosis of binomial distribution
aux_kurtosis <- function(n, p){
  kurt <- (1-6*p*(1-p))/(n*p*(1-p))
  return(kurt)
}

aux_mean(10, 0.3)
aux_variance(10, 0.3)
aux_mode(10, 0.3)
aux_skewness(10, 0.3)
aux_kurtosis(10, 0.3)
```

```{r}
# 1.3) Function bin_choose()

#' bin_choose
#' @description Calculates the number of combinations in which k successes can occur in n trials 
#' @param n 
#' @param k 
#' @return choose (numeric)

bin_choose <- function(n, k){
  check_trials(n)
  check_success(n, k)
  choose <-(factorial(n))/(factorial(k)*factorial(n-k))
  return(choose)
}
bin_choose(n = 5, k = 2)
bin_choose(5, 0)
bin_choose(5, 1:3)
```

```{r}
# 1.4) Function bin_probability()

#' bin_probability
#' @description Probability of getting k successes in n trials
#' @param k 
#' @param n 
#' @param p 
#' @return prob (numeric)
#' @export

bin_probability <- function(k, n, p){
  check_trials(n)
  check_success(n, k)
  check_prob(p)
  prob <- bin_choose(n, k) * (p^k) * (1-p)^(n-k)
  return(prob)
}

# probability of getting 2 successes in 5 trials
# (assuming prob of success = 0.5)
bin_probability(k = 2, n = 5, p = 0.5)

# probabilities of getting 2 or less successes in 5 trials
# (assuming prob of success = 0.5)
bin_probability(k = 0:2, n = 5, p = 0.5)

# 55 heads in 100 tosses of a loaded coin with 45% chance of heads
bin_probability(k = 55, n = 100, p = 0.45)
```

```{r}
# 1.5) Function bin_distribution()
library(ggplot2)

#' bin_distribution
#' @param n 
#' @param p 
#' @return frame, plot.bindis
#' @export 

bin_distribution <- function(n, p){
  frame <- matrix(nrow = n+1, ncol = 2)
  colnames(frame) <- c("successes", "probability")
  for (i in 0:n) {
    frame[i+1, 1] = i
    frame[i+1, 2] = (factorial(n)/(factorial(n-i)*factorial(i)))*p^i*(1-p)^(n-i)
  }
  print(data.frame(frame))
}

plot.bindis <- function(dis){
  ggplot(data = dis) +
  geom_bar(stat = "identity", aes(x=successes, y=probability))
}

dis1 <- bin_distribution(n = 5, p = 0.5)
plot.bindis(dis1)

```

```{r}
# 1.6) Function bin_cumulative()
library(ggplot2)

#' bin_cumulative
#' @param n 
#' @param p 
#' @return frame1, plot.bindis
#' @export

bin_cumulative <- function (n, p){
  frame1 <- matrix(nrow = n+1, ncol = 3)
  colnames(frame1) <- c("successes", "probability", "cumulative")
  for (i in 0:n) {
    frame1[i+1, 1] = i
    frame1[i+1, 2] = bin_probability(i, n, p)
    frame1[i+1, 3] = sum(frame1[0:i+1, 2])
  }
  print(data.frame(frame1))
} 

plot.bincum <- function(dis){
  ggplot(data = dis) +
  geom_point(stat = "identity",aes(x=successes, y=cumulative)) + 
  coord_cartesian() + geom_line(aes(x=successes, y=cumulative))
}

dis2 <- bin_cumulative(n = 5, p = 0.5)
plot.bincum(dis2)

```

```{r}
# 1.7) Function bin_variable()

#' bin_variable
#' @description 
#' @param trials 
#' @param prob 
#' @return 
#' @export

bin_variable <- function(trials, prob){
  check_trials(trials)
  check_prob(prob)
  binvar <-  list('trials' = trials, 'prob' = prob)
  class(binvar) = "binvar"
  binvar
}

#' @export
print.binvar <- function(binvar){
  cat('"Binomial variable" \n\n')
  cat('Parameters \n')
  cat('- number of trials:', binvar[[1]], '\n')
  cat('- prob of success :', binvar[[2]], '\n\n\n')
}

bin1 <- bin_variable(trials = 10, p = 0.3)
bin1

#' @export
summary.binvar <- function(binvar){
  summarybin <- list(
    trials <- binvar$trials,
    prob <- binvar$prob,
    mean <- aux_mean(binvar$trials,binvar$prob),
    variance <- aux_variance(binvar$trials,binvar$prob),
    mode <- aux_mode(binvar$trials,binvar$prob),
    skewness <- aux_skewness(binvar$trials,binvar$prob),
    kurtosis <- aux_kurtosis(binvar$trials,binvar$prob)
  ) 
  class(summarybin) = "summary.binvar"
  summarybin
}

#' @export
print.summary.binvar <- function(summarybin){
  cat('"Summary Binomial" \n\n')
  cat('Parameters \n')
  cat("- number of trials:", summarybin[[1]], '\n')
  cat("- prob of success :", summarybin[[2]], '\n\n')
  cat('Measures \n')
  cat('- mean    :', summarybin[[3]], '\n')
  cat('- variance:', summarybin[[4]], '\n')
  cat('- mode    :', summarybin[[5]], '\n')
  cat('- skewness:', summarybin[[6]], '\n')
  cat('- kurtosis:', summarybin[[7]], '\n')
}

bin1 <- bin_variable(trials = 10, p = 0.3)
binsum1 <- summary.binvar(bin1)
print.summary.binvar(binsum1)
```

```{r}
# 1.8) Function of measures
bin_mean <- function(n, p){
  check_trials(n)
  check_prob(p)
  aux_mean(n, p)
}
bin_mean(10, 0.3)

bin_variance <- function(n, p){
  check_trials(n)
  check_prob(p)
  aux_variance(n, p)
}
bin_variance(10, 0.3)

bin_mode <- function(n, p){
  check_trials(n)
  check_prob(p)
  aux_mode(n, p)
}
bin_mode(10, 0.3)

bin_skewness <- function(n, p){
  check_trials(n)
  check_prob(p)
  aux_skewness(n, p)
}
bin_skewness(10, 0.3)

bin_kurtosis <- function(n, p){
  check_trials(n)
  check_prob(p)
  aux_kurtosis(n, p)
}
bin_kurtosis(10, 0.3)
```


